In [1]:
import numpy as np


# 1 | Creating Arrays

In [ ]:
np.array([1,2,3])
np.zeros((3,3))
np.ones((2,2))
np.full((2,2), 7)
np.eye(3)                 # identity matrix
np.arange(0, 10, 2)
np.linspace(0, 1, 5)

In [2]:
np.array([1,2,3])


array([1, 2, 3])

In [3]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.arange(start=0, stop=10, step=2)


array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(start=0, stop=1, num=15) # create 'num' evenly spaced value from start to stop.

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

# 2 | Array Attributes

In [ ]:
arr.shape # shape - n,m
arr.ndim # the dimention 
arr.size # gives the count of the elements in the array - n * m
arr.dtype # datatype


In [14]:
arr = np.full((3,4), 6)
arr

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [15]:
arr.shape

(3, 4)

In [16]:
arr.dtype

dtype('int64')

In [ ]:
arr.size # gives the count of the elements in the array

12

# 3 | Reshaping

In [ ]:
arr.reshape(3, 2)
arr.ravel()              # flatten
arr.flatten()           # both does the same job.


In [21]:
arr = np.arange(0, 20, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
arr = arr.reshape((2,5))
arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [25]:
arr.ravel()

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
arr = arr.reshape((2,5))
arr.flatten()

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# 4 | 4. Indexing & Slicing

In [ ]:
# [start : stop : step]
arr[0, 1]
arr[:, 0]                # column
arr[1:4]                 # slice
arr[::2]
arr[arr > 5]             # boolean mask


In [28]:
arr = np.arange(0, 20, 2)
arr = arr.reshape((2,5))
arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [31]:
arr[:, 2]

array([ 4, 14])

In [33]:
arr[::1]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [34]:
arr[::-1]

array([[10, 12, 14, 16, 18],
       [ 0,  2,  4,  6,  8]])

In [36]:
arr[arr > 3]

array([ 4,  6,  8, 10, 12, 14, 16, 18])

# 5 | Vectorized Operations

In [ ]:
arr + 5
arr1 + arr2
arr * arr2
arr ** 2
np.exp(arr)
np.log(arr)
np.sqrt(arr)


# 6 | Matrix Operations

In [ ]:
np.dot(A, B)             # matrix multiplication
A.T                       # transpose
np.linalg.inv(A)          # inverse
np.linalg.det(A)          # determinant
np.linalg.eig(A)          # eigenvalues/eigenvectors


# 7 | Aggregate Functions

In [ ]:
np.sum(arr)
np.mean(arr)
np.std(arr)
np.var(arr)
np.min(arr)
np.max(arr)
np.argmax(arr)
np.argmin(arr)


In [38]:
arr = np.arange(0, 20, 2)
arr = arr.reshape((2,5))
arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
arr.argmax() # for the 2D matrix it flatten the array first anf then find the index.

9

In [41]:
# to get the actual 2D index.
np.unravel_index(np.argmax(arr), arr.shape)


(1, 4)

In [40]:
arr.argmin()

0

In [42]:
np.unravel_index(np.argmin(arr), arr.shape)


(0, 0)

# 8 | Broadcasting

In [ ]:
arr + 5
arr + np.array([1,2,3])   # row-wise broadcast


# 9 | Stacking & Concatenation

In [ ]:
np.concatenate([a, b], axis=0)
np.vstack([a, b])
np.hstack([a, b])


In [43]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

In [ ]:
np.concatenate([a, b], axis=0) # row wise stacking vertical stacking


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.concatenate([a, b], axis=1) # column stacking horizondal stacking


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.vstack([a, b]) # same as axis = 0


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# 10 | Random Number Generation

In [ ]:
np.random.seed(42)
np.random.rand(3, 3) # values from 0 - 1
np.random.randn(3, 3) # values from random normal distribution.
np.random.randint(0, 10, size=(3,3))


array([[2, 6, 3],
       [8, 2, 4],
       [2, 6, 4]])

In [50]:
np.random.seed(42)


In [48]:
np.random.rand(3, 3)


array([[0.45049925, 0.01326496, 0.94220176],
       [0.56328822, 0.3854165 , 0.01596625],
       [0.23089383, 0.24102547, 0.68326352]])

In [ ]:
np.random.randn(3, 3)
# Random Normal distribution

# Values follow a standard normal distribution:

# mean = 0

# standard deviation = 1


array([[-0.74240684,  1.13022819,  0.37311891],
       [-0.38647295, -1.15877024,  0.56611283],
       [-0.70445345, -1.3779393 , -0.35311665]])

# 11 | Useful Utilities

In [ ]:
np.unique(arr) # list of all the unique numbers
np.sort(arr) # row-wise sorting
np.argsort(arr) # row-wise sorting index position.
np.clip(arr, 0, 1) # forces all values to stay within the range 0 to 1.


In [52]:
arr = np.random.randint(1, 10, size=(2,4))
arr

array([[5, 4, 8, 8],
       [3, 6, 5, 2]])

In [55]:
np.unique(arr)


array([2, 3, 4, 5, 6, 8])

In [ ]:
np.sort(arr) # row-wise sorting


array([[4, 5, 8, 8],
       [2, 3, 5, 6]])

In [53]:
np.argsort(arr)


array([[1, 0, 2, 3],
       [3, 0, 2, 1]])

In [54]:
np.clip(arr, 0, 1)


array([[1, 1, 1, 1],
       [1, 1, 1, 1]])