In [1]:
# Linear regression
#import the libraries
import numpy as np


In [8]:
#creat the dataset
#giging the input as one feature value and last one is output
data=np.array([[37.8,39.3,45.9,41.3],[22.1,10.4,18.3,18.5]])
data

array([[37.8, 39.3, 45.9, 41.3],
       [22.1, 10.4, 18.3, 18.5]])

In [10]:
#transpose it 
data.T


array([[37.8, 22.1],
       [39.3, 10.4],
       [45.9, 18.3],
       [41.3, 18.5]])

In [34]:
#split is as fetures and output
X=data[:][0]
y=data[:][1]
weight=0.2
bias=0.0

In [36]:
#find the output
def predict(X,weight,bias):
    return np.dot(X,weight)+bias


array([7.56, 7.86, 9.18, 8.26])

In [47]:
#step-2---Cost function
def cost_function(X,weight,bias,y):
    N=len(X)
    y_pred=predict(X,weight,bias)
    diff=(y-y_pred)**2
    return sum(diff)/N  
#cost_function(X,weight,bias,y)

101.47380000000003

In [42]:
#step-3----update weights to reduce error using the gradient decent
def update_weight(X,weight,bias,y):
    w_deri=0
    bias_deri=0
    

211.41159999999996