- eiga values and eigan vectors

# Q1: 779. Boolean Mask Filter




Given a NumPy array of numbers and a threshold, return all elements that are strictly greater than the threshold. Implement the function using NumPy boolean masking. The result should be a Python list of the filtered elements in their original order.

nput
1
2
arr = [1,5,2,8,3]
threshold = 3
Expected Output
[5,8]

In [5]:
import numpy as np

def filter_greater(arr: list, threshold: float) -> list:
    """Write your solution here."""
    arr = np.array(arr)
    mask = arr > threshold
    print(mask)
    res = arr[mask]
    print(res)
    return res

# Platform requirement: Call the function at the end
filter_greater([1,5,2,8,3], 3)

[False  True False  True False]
[5 8]


array([5, 8])

# Q2: 161. Change of basis

Implement change of basis for a vector, which lets you express the same geometric vector using different coordinate systems. You'll compute the coordinates of a vector in a new basis using a basis matrix.

$$[v]_B = B^{-1}v$$

**Input**
```
B = [
  [1, 1],
  [0, 1]
]
v = [2, 1]
```
**Expected Output**
```
[1, 1]
```

In [6]:
import numpy as np

def change_of_basis(v, B):
    """
    Converts vector coordinates from the standard basis to a new basis.

    Args:
        v (np.ndarray): Vector in standard coordinates of length n.
        B (np.ndarray): Basis matrix of shape (n, n), where columns
            are basis vectors.

    Returns:
        np.ndarray: The coordinates of v in the basis defined by B.
    """
    B = np.array(B)
    v = np.array(v)
    
    B_inv = np.linalg.inv(B)
    v_new = B_inv @ v
    
    return v_new

# Example Usage
B = [
  [1, 1],
  [0, 1]
]
v = [2, 1]
result = change_of_basis(v, B)
result

array([1., 1.])

Inverstible if: there exist a matrix A . A_inv = I and A_inv . A = I

Concept: Expressing a vector in a different coordinate system

Normally, when you write a vector like v = [2, 1], you mean:

2 units along the standard x-axis [1,0]
1 unit along the standard y-axis [0,1]
But what if your coordinate system uses different axes (a new basis B)?

A basis matrix B has the new axes as its columns. To find the coordinates of v in that new system:

$$[v]_B = B^{-1} \cdot v$$

Intuition: You're asking — "how much of each new basis vector do I need to reconstruct v?"

```
B = [[1,1],    ← new axes are [1,0] and [1,1]
     [0,1]]
B = [b1 b2]
each column is a new basis, so  [1,0] (b1) is x axis, and [1,1] (b2) is the new y axis.

v = [2, 1]

B⁻¹ · v = [1, 1]   ← in the new system, v is expressed as [1, 1]

This is finding "“How much of b1 and b2 do I need to build v?”"
This means: 1×[1,0] + 1×[1,1] = [1,0] + [1,1] = [2,1] ✓
```
Real-world use: PCA, 3D graphics, signal processing — any time you need to switch between coordinate systems.

# Q3: Column-wise metrics

In [4]:
import numpy as np 

def col_metric(m):
    m = np.array(m)
    d = {}
    d["max"] = m.max(axis=0)
    d["min"] = m.min(axis=0)
    d["mean"] = m.mean(axis=0)
    return d

matrix = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
]
col_metric(matrix)

{'max': array([7, 8, 9]), 'min': array([1, 2, 3]), 'mean': array([4., 5., 6.])}

# Q4: 313. Cosine similarity


Compute cosine similarity between two vectors, a common linear algebra measure of how aligned they are. It’s especially useful when you care about direction more than magnitude.

Input
1
2
x = [1,2,3]
y = [4,5,6]
Expected Output
0.9746318461970762

In [5]:
import numpy as np

def cosine_similarity(x, y):
    """
    Computes cosine similarity between two vectors.

    Cosine similarity is defined as:
        cos(x, y) = (x · y) / (||x|| * ||y||)

    Args:
        x (np.ndarray): First vector.
        y (np.ndarray): Second vector.

    Returns:
        float: Cosine similarity score.
    """
    x = np.array(x)
    y = np.array(y)
    top = x @ y
    return top / (np.linalg.norm(x) * np.linalg.norm(y))

# Example Usage
x = [1,2,3]
y = [4,5,6]
result = cosine_similarity(x, y)
result

np.float64(0.9746318461970762)

# Q5: 174. Determinant properties


## Concept: Vectors, Matrices, Transformations & Determinant

---

### Vector
Just an arrow described by numbers.
```
[2, 3] = go 2 right, 3 up
```

---

### Matrix
- normally matrix is a set of vectors, here we are using it on a vector. 
A grid of numbers that acts as a **rule for moving vectors**.
```
A = [[2, 0],
     [0, 3]]   ← stretch x by 2, stretch y by 3
```

---

### Transformation
- we are forming a shape by few vectors, lets say 3 vectors here, v1, v2,v3, v4. 
- We apply the A matrix on all 4 vectors. 
Apply the matrix to **every point in space simultaneously**.
```
Before                   After A × every point
  B───C                    B'────────C'
  |   |      ──────►        |        |
  A───D                    A'────────D'

unit square (area=1)      rectangle (area=6)
```


---

### Determinant
- simple how much the area of the shape changed after we apply A to all the vectors.
- this will be always same, because we are applying the same A to all the vectors, it will transform all the vectors in the same way. 
- so regardless of the vector values, the area will change depend on the A only.

> Measures **how much the transformation scaled the area**.

$$\det(A) = \text{area after} / \text{area before}$$

**2×2 Formula:**
$$\det\begin{pmatrix}a & b\\c & d\end{pmatrix} = ad - bc$$

**Example:**
```
A = [[2, 1],      det = (2×3) - (1×5) = 6 - 5 = 1
     [5, 3]]      area perfectly preserved
```


**Example of the area change**:
```
A = [[2, 0, 0],
     [0, 3, 0],
     [0, 0, 4]]

det(A) = 2 × 3 × 4 = 24
```
```
v1 = [1,0,0]   v2 = [0,1,0]   v3 = [0,0,1]

3 vectors → put them as rows → take det → that gives the volume
volume before = det([[1,0,0],[0,1,0],[0,0,1]]) = 1

```
After multiplying A.
```
Av1 = [2,0,0]   Av2 = [0,3,0]   Av3 = [0,0,4]

volume after = det([[2,0,0],[0,3,0],[0,0,4]]) = 2×3×4 = 24 ✓
```

---

### Determinant Quick Reference

| det value | Meaning | Invertible? |
|---|---|---|
| `> 1` | Space expands (area grows) | Yes |
| `= 1` | Area preserved (rotation/shear) | Yes |
| `0 < det < 1` | Space shrinks | Yes |
| `< 0` | Area scaled + orientation flipped (mirror) | Yes |
| `= 0` | Collapsed to a line — information destroyed | **No** |


## No. Determinant is only defined for square matrices.

Why?
Remember what determinant means geometrically:

```
2×2 matrix  →  measures area scaling   (2D → 2D)
3×3 matrix  →  measures volume scaling (3D → 3D)
The transformation must go from and to the same space.


2×3 matrix transforms 3D → 2D
         ↑
   input and output are different dimensions
   "how much did area scale?" doesn't make sense
Intuition

Square matrix:    n×n   →  n inputs, n outputs  →  det makes sense
Non-square:       2×3   →  3 inputs, 2 outputs  →  det undefined
It's like asking "what's the volume of a flat sheet of paper?" — the question doesn't apply.
```

### How to Find Determinant Using Row Operations (Step-by-Step)
### No. Determinant is only defined for square matrices.


**Goal:** Convert matrix to upper triangular using row ops, then multiply the diagonal.
find upper diagonal using the Gaussian elimination:

$$\det(A) = (-1)^k \times \prod \text{diagonal elements}$$

where `k` = number of row swaps.
1. we find a non-zero element for a column
2. and make all the below value as zero.
---

**Example:**
```
A = [[0, 2, 1],
     [1, -1, 3],
     [4,  0, 2]]
```

---

**Step 1: First column has 0 at top — need a non-zero pivot. Swap row 0 and row 1.**
```
[[0, 2, 1],          [[1, -1, 3],
 [1,-1, 3],   ──►     [0,  2, 1],     swap count k = 1  →  sign = -1
 [4, 0, 2]]           [4,  0, 2]]
```

---

**Step 2: Eliminate below pivot (col 0). Pivot = A[0][0] = 1**
```
row2 = row2 - (4/1) × row0
     = [4,0,2] - 4×[1,-1,3]
     = [4-4, 0+4, 2-12]
     = [0, 4, -10]

[[1, -1,   3],
 [0,  2,   1],
 [0,  4, -10]]
```

---

**Step 3: Eliminate below pivot (col 1). Pivot = A[1][1] = 2**
```
row2 = row2 - (4/2) × row1
     = [0,4,-10] - 2×[0,2,1]
     = [0-0, 4-4, -10-2]
     = [0, 0, -12]

[[1, -1,   3],   ← upper triangular ✓
 [0,  2,   1],
 [0,  0, -12]]
```

---

**Step 4: Multiply diagonal × sign**
```
diagonal = 1 × 2 × -12 = -24
sign     = (-1)^1 = -1       ← 1 swap happened

det = -1 × -24 = 24
```

---

**Verify with numpy:**
```python
import numpy as np
A = [[0,2,1],[1,-1,3],[4,0,2]]
np.linalg.det(A)   # → 24.0  ✓
```

You'll practice core determinant properties that show up a lot in linear algebra interviews, like how row operations affect the determinant. Given a square matrix as a NumPy array, compute its determinant using only simple row operations and a recursive base case.

$$\det(A) = (-1)^k \prod_{i=1}^{n} U_{ii}$$

**Input**
```
A = [
  [2, 1],
  [5, 3]
]
```
**Expected Output**
```
1
```

In [8]:
import numpy as np

def determinant_via_row_ops(A):
    A = np.array(A, dtype=float)
    n = len(A)
    sign = 1
    # For each column: finding the upper diagonal element using hte Gaussian elimination
    # Row Redection method:
    for col in range(n):
        
        # Find non-zero pivot in this column
        pivot_row = None
        for row in range(col, n):
            # for each row check the diagonal element is non-zero. 
            if A[row][col] != 0:
                pivot_row = row
                break
        if pivot_row is None:
            return 0 # there are no non-zero row. this is not invertable -> determinant = 0. 
        
        # once you find the non-zero one we need to swap it.
        if pivot_row != col:
            A[[col, pivot_row]] = A[[pivot_row, col]]
            # A[col], A[pivot_row] = A[pivot_row], A[col] - >this breaks in numpy
            sign *= -1  # each swap flips the sign
        
        # Eliminate below pivot, make all the values below pivot us zero.
        for row in range(col + 1, n): # make all teh value below
            # we swapped the element, so the pivot is in now - doagonal which is A[col, col]
            factor = A[row, col] / A[col, col]
            A[row] -= factor * A[col]
    # det = sign × product of diagonal
    return sign * np.prod(np.diag(A))

# Example Usage
A = [
  [0, 2, 1],
  [1, -1, 3],
  [4, 0, 2]
]
determinant_via_row_ops(A)  # → 24.0

np.float64(24.0)

# Q6: 1577. Matrix rank




Compute the rank of a matrix, which is the number of linearly independent rows (or columns) in a matrix. This helps you understand how much "unique information" the matrix contains in a linear algebra sense.

The rank can be defined as the number of non-zero singular values from an SVD:

$$\text{rank}(A) = |\{ i : \sigma_i > \varepsilon \}|$$

where $\sigma_i$ are the singular values of $A$ and $\varepsilon$ is a small tolerance.

**Input**
```
A = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
]
```
**Expected Output**
```
2
```

- we can find it using 2 methods:
- **Both the methods can be done on a non-square matrix**
- row reduction method:
```
After getting the upper diagonal matrix:
[[1,  2,  3],
 [0, -3, -6],
 [0,  0,  0]]  ← zero row

```
Count non-zero rows = 2 → rank = 2

- SVD Method:
SVD breaks A into singular values σ. Each non-zero σ = one independent dimension.

```
A = [[1,2,3],[4,5,6],[7,8,9]]

singular values σ = [16.11, 1.07, ~0.0]
                                   ↑
                              essentially 0

count(σ > ε) = 2  →  rank = 2

```

```
Row reduction:   works well for exact integer matrices
SVD:             works well for real/noisy data
                 "how many dimensions actually matter?"
                 used in PCA, compression, ML

```

In [ ]:
import numpy as np

def matrix_rank(A, eps=1e-10):
    A = np.array(A, dtype=float)
    m, n = A.shape
    rank = 0
    current_row = 0  # next row slot available for a pivot

    for col in range(n):
        # Find non-zero pivot in this column
        pivot_row = None
        for row in range(current_row, m):
            if abs(A[row, col]) > eps:
                pivot_row = row
                break

        if pivot_row is None:
            continue  # entire column is ~zero, skip to next column

        # Swap pivot row into current position
        if pivot_row != current_row:
            A[[current_row, pivot_row]] = A[[pivot_row, current_row]]

        # here current_row is different from col, because we are skipping the zero columns.
        # so if the first col is fuly zero, 

        # Normalize pivot row so pivot = 1
        A[current_row] = A[current_row] / A[current_row, col]

        # Eliminate all values below pivot to zero
        
        for row in range(current_row + 1, m):
            factor = A[row, col] / A[current_row, col]
            A[row] -= factor * A[current_row]

        rank += 1
        current_row += 1 # (always current_row == rank)

    return rank

# Example Usage
A = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
]
matrix_rank(A)  # → 2

### Step-by-Step Example — Matrix Rank

```
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

rank = 0,  current_row = 0
```

---

**col=0:** Search col 0 from row 0 → A[0,0]=1 → `pivot_row=0`
```
No swap needed (pivot_row == current_row == 0)

Normalize row0: [1,2,3] / 1 = [1, 2, 3]

Eliminate below:
  factor = A[1,0] / A[0,0] = 4/1 = 4
  row1 = [4,5,6] - 4×[1,2,3] = [0, -3, -6]

  factor = A[2,0] / A[0,0] = 7/1 = 7
  row2 = [7,8,9] - 7×[1,2,3] = [0, -6, -12]

[[1,  2,   3],
 [0, -3,  -6],
 [0, -6, -12]]

rank = 1,  current_row = 1
```

---

**col=1:** Search col 1 from `current_row=1` → A[1,1]=-3 → `pivot_row=1`
```
No swap needed (pivot_row == current_row == 1)

Normalize row1: [0,-3,-6] / -3 = [0, 1, 2]

Eliminate below:
  factor = A[2,1] / A[1,1] = -6/1 = -6
  row2 = [0,-6,-12] - (-6)×[0,1,2] = [0, -6+6, -12+12] = [0, 0, 0]

[[1,  2,  3],
 [0,  1,  2],
 [0,  0,  0]]  ← zero row

rank = 2,  current_row = 2
```

---

**col=2:** Search col 2 from `current_row=2` → A[2,2]=0 → `pivot_row=None` → skip
```
rank = 2,  current_row = 2  (nothing changed)
```

---

**Final:**
```
[[1,  2,  3],
 [0,  1,  2],
 [0,  0,  0]]  ← 2 non-zero rows → rank = 2

row3 = -1×row1 + 2×row2  → not independent → doesn't count
```

### Step-by-Step Example — why `current_row` and `col` are separate

```
A = [[0, 1, 2],
     [0, 3, 6],
     [0, 0, 5]]
```

---

**col=0:** Search col 0 for non-zero → all zeros → `pivot_row = None` → skip
```
current_row = 0   rank = 0   (nothing changed)
```

---

**col=1:** Search col 1 from `current_row=0` → A[0,1]=1 → `pivot_row=0`
```
No swap needed (pivot_row == current_row == 0)

Normalize row0: [0,1,2] / 1 = [0, 1, 2]

Eliminate below:
  row1 = [0,3,6] - 3×[0,1,2] = [0, 0, 0]
  row2 = [0,0,5] - 0×[0,1,2] = [0, 0, 5]

[[0, 1, 2],
 [0, 0, 0],
 [0, 0, 5]]

current_row = 1   rank = 1
```

---

**col=2:** Search col 2 from `current_row=1` → A[1,2]=0, A[2,2]=5 → `pivot_row=2`
```
Swap needed (pivot_row=2 != current_row=1):

[[0, 1, 2],
 [0, 0, 5],   ← swapped up
 [0, 0, 0]]

Normalize row1: [0,0,5] / 5 = [0, 0, 1]

Eliminate below:
  row2 = [0,0,0] - 0×[0,0,1] = [0, 0, 0]

[[0, 1, 2],
 [0, 0, 1],
 [0, 0, 0]]

current_row = 2   rank = 2
```

---

**Final: rank = 2**

---

**Why `col` and `current_row` must be separate:**
```
col          →  0    1    2
current_row  →  0    0    1    2
```
When `col=0` was all zeros, `col` moved forward but `current_row` stayed at 0.
If they were the same variable, col=1 would have searched from row=1 and **missed the pivot at row=0**.

```
col moves forward always
current_row moves forward only when a pivot is found
```

# Q7: 75. One-Hot Encode Labels

In [7]:
#Gven a list of integer class labels and the total number of classes C, 
# implement a function that returns the one-hot encoded matrix of shape (n, C). 
# Each row corresponds to a label with a 1 at its class index and 0 elsewhere. Use NumPy for the implementation.
import numpy as np

def one_hot_encode(labels: list, num_classes: int) -> list:
    import numpy as np
    arr = np.array(labels, dtype=int)
    print(np.eye(num_classes, k=1, dtype=int)) # this is the eye function, same as identy matrix. but we can set the kth diagonal to be 1. 

    # Here we are simply taking the index values,
    print(np.eye(num_classes, k=0, dtype=int)[[1,2]])
    # [[0 1 0]
    #  [0 0 1]]
    one_hot = np.eye(num_classes, dtype=int)[arr] # so we will get the value in that index as 1. 
    
    return one_hot.tolist()

labels = [0,2,1,2]
num_classes = 3

# Platform requirement: Call the function at the end
one_hot_encode(labels, num_classes)


[[0 1 0]
 [0 0 1]
 [0 0 0]]
[[0 1 0]
 [0 0 1]]


[[1, 0, 0], [0, 0, 1], [0, 1, 0], [0, 0, 1]]

In [ ]:
# can do using advanced indexing too.
arr = np.zeros((3,4))
a = [0,1,2]
b = [0,0,3]
# can keep 2 lists for indexing.
arr[a, b ] = 1
arr

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# can do using advanced indexing too.
arr = np.zeros((3,4))
a = 0 # this will be broadcasted 
b = [0,0,3]
# can keep 2 lists for indexing.
arr[a, b ] = 1
arr

array([[1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Q8: 1336. Pairwise Euclidean Distance




Given two sets of 2D points, compute the full pairwise Euclidean distance matrix using NumPy broadcasting — no explicit Python loops.

$$d(a, b) = \sqrt{\sum_{i}(a_i - b_i)^2}$$

**Input**
```
points_a = [
  [1, 2],
  [3, 4]
]
points_b = [
  [5, 6],
  [7, 8]
]
```
**Expected Output**
```
[
  [5.656854249492381, 8.48528137423857],
  [2.8284271247461903, 5.656854249492381]
]
```

In [ ]:
import numpy as np

def pairwise_euclidean(points_a: list, points_b: list) -> list:
    import numpy as np
    A = np.array(points_a, dtype=float)
    B = np.array(points_b, dtype=float)
    if A.size == 0:
        return []
    diff = A[:, None, :] - B[None, :, :]
    dis = np.linalg.norm(diff, axis=2)
    return dis

points_a = [
  [0, 0],
  [1, 0]
]
points_b = [
  [0, 0]
]


# Platform requirement: Call the function at the end
pairwise_euclidean(points_a, points_b)

array([[0.],
       [1.]])

In [ ]:
import numpy as np


# Other wya to do it, if you forgot your 3d prodcasting,
def pairwise_euclidean(points_a: list, points_b: list) -> list:
    import numpy as np
    A = np.array(points_a, dtype=float)
    B = np.array(points_b, dtype=float)
    if A.size == 0:
        return []
    dis = [ ]
    for row in range(A.shape[0]):
        cur_row = A[row, :]
        d = np.linalg.norm(cur_row - B, axis=1)
        dis.append(d)

    return dis

points_a = [
  [1, 2],
  [3, 4]
]
points_b = [
  [5, 6],
  [7, 8]
]


# Platform requirement: Call the function at the end
pairwise_euclidean(points_a, points_b)

[array([5.65685425, 8.48528137]), array([2.82842712, 5.65685425])]

# Concepts to Know (No Coding Needed)



---

## Inverse

A matrix `A` has an inverse `A⁻¹` such that:
```
A @ A⁻¹ = I     (identity matrix)
```

**When does it exist?**
```
det(A) ≠ 0   →  invertible
det(A) = 0   →  not invertible (singular) — columns are linearly dependent
```

**Where it shows up in ML:**
```
Linear regression normal equation:
  w = (XᵀX)⁻¹ Xᵀy

If features are correlated → XᵀX is singular → can't invert
Fix: add regularization → (XᵀX + λI)⁻¹  ← always invertible
```

**In numpy:** `np.linalg.inv(A)`

---

## Eigenvalues & Eigenvectors

### What is it?

Usually a matrix rotates AND stretches a vector:
```
A = [[2, 1],
     [1, 2]]

v = [1, 0]
A @ v = [2, 1]    ← changed direction AND length
```

But for **special vectors**, the matrix only stretches — direction stays the same:
```
v = [1, 1]
A @ v = [3, 3] = 3 × [1, 1]    ← same direction, just 3× longer
```
That special vector is an **eigenvector**. The stretch amount `3` is the **eigenvalue**.

```
A @ v = λ × v

v  →  eigenvector   (direction that survives the transformation)
λ  →  eigenvalue    (how much it stretches)
```

---

### Finding eigenvectors = finding directions A doesn't rotate, finding a vector which will not change the direction by appyling A.

```
most vectors:    A changes direction + length
eigenvectors:    A changes length only  ←  direction locked
```

Every matrix has directions it "wants" to stretch along — eigenvectors are those directions.

```
λ > 1        →  stretched
λ = 1        →  unchanged
0 < λ < 1   →  shrunk
λ < 0        →  flipped + scaled
λ = 0        →  collapsed to zero  ← matrix is singular
```

---

### Concrete example — diagonal matrix (easy)

```
A = [[3, 0],
     [0, 2]]

v1 = [1, 0]   →   A @ v1 = [3, 0] = 3 × [1, 0]   λ1 = 3
v2 = [0, 1]   →   A @ v2 = [0, 2] = 2 × [0, 1]   λ2 = 2
```
x-axis stretches by 3, y-axis stretches by 2. Eigenvectors = the axes themselves.

---

### Concrete example — non-diagonal matrix

```
A = [[2, 1],
     [1, 2]]
```

Solve `det(A - λI) = 0`:
```
det([[2-λ,  1  ],
     [ 1,  2-λ]]) = 0

(2-λ)² - 1 = 0
λ² - 4λ + 3 = 0
(λ-3)(λ-1) = 0

λ1 = 3,  λ2 = 1
```

Find eigenvectors by plugging λ back:
```
λ1 = 3  →  v1 = [1,  1]   (normalize: [0.707,  0.707])
λ2 = 1  →  v2 = [1, -1]   (normalize: [0.707, -0.707])
```

Verify:
```
A @ [1, 1]  = [3, 3] = 3 × [1, 1]   ✓
A @ [1,-1]  = [1,-1] = 1 × [1,-1]   ✓
```

---

### Key properties
```
number of eigenvalues  =  n   (for n×n matrix)
sum of eigenvalues     =  trace(A)   (sum of diagonal)
product of eigenvalues =  det(A)

if det = 0  →  one eigenvalue is 0  →  not invertible
```

---

### Where it shows up in ML

**PCA:**
```
eigenvectors of covariance matrix  =  principal components (directions of max variance)
eigenvalues                        =  how much variance each direction holds

sort by eigenvalue descending:
  PC1  →  most variance
  PC2  →  second most
```

**Hessian / gradient descent:**
```
eigenvalues of Hessian  =  curvature of loss in each direction
large eigenvalue        →  steep, take small steps
small eigenvalue        →  flat, can take larger steps

very different eigenvalues → gradient descent oscillates
that's why Adam helps
```

---

**In numpy:** `np.linalg.eig(A)` → returns `(eigenvalues, eigenvectors)`

---

## Quick Reference
```
np.linalg.inv(A)          →  inverse
np.linalg.eig(A)          →  eigenvalues + eigenvectors
np.linalg.svd(A)          →  singular value decomposition
np.linalg.det(A)          →  determinant
np.linalg.matrix_rank(A)  →  rank
```