# Q1: 1449. Feature standardization


Standardize features so they have zero mean and unit variance (z-score normalization). Compute **per column** (feature-wise), not per row.

$$z_{ij} = \frac{x_{ij} - \mu_j}{\sigma_j}$$

where $\sigma_j = \sqrt{\frac{1}{n}\sum_{i=1}^{n}(x_{ij} - \mu_j)^2}$ (population std, `ddof=0`)

**Constraints**
- No `sklearn.preprocessing.StandardScaler`
- Return nested Python list, not NumPy array

**Input**
```
X = [
  [1, 2],
  [3, 4],
  [5, 6]
]
```
**Expected Output**
```
[
  [-1.2247448713915892, -1.2247448713915892],
  [0.0, 0.0],
  [1.2247448713915892, 1.2247448713915892]
]
```

In [32]:
import numpy as np

def standardize_features(X):
    """
    Standardizes each feature (column) of X using z-score normalization.

    Args:
        X (list[list[float]]): 2D dataset of shape (n_samples, n_features).

    Returns:
        list[list[float]]: Standardized dataset with the same shape as X.
    """
    X = np.array(X, dtype=float)
    col = np.shape(X)[1]
    for c in range(col):
        # find the std, and mean
        print(X[:, c])
        X[:,c ] = (X[:, c] - np.mean(X[:,c]) ) / np.std(X[:, c])
    return X
X = [
  [1, 10],
  [2, 20],
  [3, 30]
]
# Example Usage
result = standardize_features(X)
result

[1. 2. 3.]
[10. 20. 30.]


array([[-1.22474487, -1.22474487],
       [ 0.        ,  0.        ],
       [ 1.22474487,  1.22474487]])

In [33]:
def standardize_features(X):
    """
    Standardizes each feature (column) of X using z-score normalization.

    Args:
        X (list[list[float]]): 2D dataset of shape (n_samples, n_features).

    Returns:
        list[list[float]]: Standardized dataset with the same shape as X.
    """
    # Convert input list to NumPy array for vectorized operations
    arr = np.array(X, dtype=float)

    # Compute column-wise mean and population standard deviation
    mean = np.mean(arr, axis=0)
    std = np.std(arr, axis=0, ddof=0)

    # Standardize using broadcasting
    standardized = (arr - mean) / std

    # Convert back to nested Python list
    return standardized.tolist()

# Q2: 


Handle high-cardinality categorical features by keeping only the top-K most frequent categories and replacing the rest with `"OTHER"`.

$$\text{enc}(x) = \begin{cases} x & \text{if } x \in \text{TopK}(X, K) \\ \text{"OTHER"} & \text{otherwise} \end{cases}$$

**Input**
```
k = 2
values = ["red", "blue", "red", "green", "blue", "yellow", "blue"]
```
**Expected Output**
```
["red", "blue", "red", "OTHER", "blue", "OTHER", "blue"]
```

In [34]:
# import numpy as np
# from collections import defaultdict

# def topk_other_encode(values, k):
#     """
#     Encodes a high-cardinality categorical column by keeping only the top-k
#     most frequent categories and mapping the rest to "OTHER".

#     Args:
#         values (np.ndarray): Categorical values (one column).
#         k (int): Number of most frequent categories to keep.

#     Returns:
#         np.ndarray: Encoded values where rare categories are replaced by "OTHER".
#     """
#     d = defaultdict(int)
#     for i in range(len(values)):
#         d[values[i]] += 1
#     max_freq = np.sort(list(d.values()))[:k]
#     print(d, max_freq)
#     for ind, ele in enumerate(values):
#         if d[ele] not in max_freq:
#             values[ind] = "OTHER"
#     return values 
# k = 2
# values = ["b","a","c","a","b","c"]
# result = topk_other_encode(values, k)
# result

In [35]:
values = ["b","a","c","a","b","c"]
v = np.array(values)
v[[1,2]]

array(['a', 'c'], dtype='<U1')

In [ ]:
import numpy as np
from collections import defaultdict

def topk_other_encode(values, k):
    """
    Encodes a high-cardinality categorical column by keeping only the top-k
    most frequent categories and mapping the rest to "OTHER".

    Args:
        values (np.ndarray): Categorical values (one column).
        k (int): Number of most frequent categories to keep.

    Returns:
        np.ndarray: Encoded values where rare categories are replaced by "OTHER".
    """
    # Get unique values and their counts
    # np.unique returns unique values sorted lexicographically
    u, c = np.unique(values, return_counts=True)
    print("count,", u,c)

    # Sort by count (desc), then by value (asc) for ties
    # np.lexsort uses the last key as primary key
    sort_idx = np.lexsort((u, -c))
    # names  = ['Bob', 'Alice', 'Bob',   'Alice']
    # scores = [  90,     85,     85,      90  ]
    # idx = np.lexsort((scores, names))

    # sort by names first (primary), then scores (secondary) as tiebreaker:

    # Alice 85   ← Alice comes first, lower score first
    # Alice 90
    # Bob   85
    # Bob   90

    # idx = [1, 3, 2, 0] index of the names array (first input.)


    print(sort_idx)

    # Select the top-k categories
    top_k_vals = u[sort_idx[:k]]

    # Create a mask where True indicates the value is in the top-k set
    mask = np.isin(values, top_k_vals)

    # Return values where mask is True, else "OTHER"
    # np.where will automatically handle string dtype promotion if needed
    return np.where(mask, values, "OTHER")
k = 2
values = ["b","a","c","a","b","c"]
result = topk_other_encode(values, k)
result

count, ['a' 'b' 'c'] [2 2 2]
[0 1 2]


array(['b', 'a', 'OTHER', 'a', 'b', 'OTHER'], dtype='<U5')

# q3: 27. Impute Missing Values




Given a list containing integers, floats, and None values, replace each None with the mean of the non-missing numeric values.

If there are no valid numeric values to compute a mean, the computed mean is None, and all None entries should remain None.

Return a new list with the same length and order as the input.
Input
values = [1,None,3.5,None,2]
Expected Output
[1,2.1666666666666665,3.5,2.1666666666666665,2]

In [2]:
import numpy as np

def fill_missing_with_mean(values: list) -> list:
    """
    Replace None entries with the mean of valid numeric values.

    Returns:
        list: New list with None values imputed.
    """
    values = np.array(values,)
    mask = values != None
    # print(np.mean(values), ) -> we cant find hte mean without imputing it.
    # # Calculating the mean of non-NaN values
    total = 0.0
    count = 0

    for v in values:
        if v is not None:
            total += float(v)
            count += 1

    mean = (total / count) if count > 0 else None

    return np.where(mask, values, mean)

values = [1,None,3.5,None,2]

# Platform requirement: Call the function at the end
fill_missing_with_mean(values)

array([1, 2.1666666666666665, 3.5, 2.1666666666666665, 2], dtype=object)

In [4]:
# below is with numpy
def fill_missing_with_mean(values: list) -> list:
    arr = np.array(values, dtype=float)   # None → nan
    mean = np.nanmean(arr)                # ignores nan
    # same like this we have nanstd() 
    arr = np.where(np.isnan(arr), mean, arr)  # fill nan with mean
    return arr.tolist()
values = [1,None,3.5,None,2]

# Platform requirement: Call the function at the end
fill_missing_with_mean(values)

[1.0, 2.1666666666666665, 3.5, 2.1666666666666665, 2.0]

# Q4: 218. Mean and median imputation




Impute missing values (marked as `-1`) per column using either mean or median of the non-missing values in that column.

$$x'_{i,j} = \begin{cases} x_{i,j} & \text{if } x_{i,j} \neq -1 \\ \mu_j \text{ or } m_j & \text{if } x_{i,j} = -1 \end{cases}$$

where $\mu_j$ = mean of column $j$ (ignoring -1), $m_j$ = median of column $j$ (ignoring -1).

**Input**
```
X = [
  [1, -1, 10],
  [2,  5, -1],
  [-1, 7, 30]
]
strategy = ["mean", "median", "mean"]
```
**Expected Output**
```
[
  [1,   6, 10],
  [2,   5, 20],
  [1.5, 7, 30]
]
```

In [ ]:
import numpy as np

def impute_mean_median(X, strategy):
    """
    Imputes missing values in a 2D dataset using per-column mean or median.

    Args:
        X (list[list[float]]): 2D data table of shape (n_samples, n_features).
            Missing values are represented by -1.
        strategy (list[str]): List of length n_features where each entry is
            either "mean" or "median", indicating how to impute that column.

    Returns:
        list[list[float]]: A new 2D list with missing values imputed.
    """
    # Convert input to NumPy array for vectorized operations
    arr = np.array(X, dtype=float)
    n_rows, n_cols = arr.shape

    # compute per column imputation values.
    impute_values = np.zeros(n_cols, dtype=float)
    for col in range(n_cols):
        print(col)
        col_val = arr[:, col]
        valid = arr[:, col] != -1
        print(col_val[valid])
        if strategy[col] == "mean":
            impute_values[col] = np.mean(col_val[valid])
        else:
            impute_values[col] = np.median(col_val[valid])
    print(impute_values)

    # Replace missing values per column
    for j in range(n_cols):
        missing = arr[:, j] == -1
        arr[missing, j] = impute_values[j]
    
    return arr


X = [
  [1, -1, 10],
  [2, 5, -1],
  [-1, 7, 30]
]
strategy = ["mean","median","mean"]
result = impute_mean_median(X, strategy)
result

0
[1. 2.]
1
[5. 7.]
2
[10. 30.]
[ 1.5  6.  20. ]


array([[ 1. ,  6. , 10. ],
       [ 2. ,  5. , 20. ],
       [ 1.5,  7. , 30. ]])

In [77]:
X = [
  [-1, 2, -1, 8],
  [3, -1, 5, -1],
  [3, 4, 7, 8],
  [9, 4, -1, 0]
]
strategy = ["median","mean","median","mean"]
result = impute_mean_median(X, strategy)
result

0
[3. 3. 9.]
1
[2. 4. 4.]
2
[5. 7.]
3
[8. 8. 0.]
[3.         3.33333333 6.         5.33333333]


array([[3.        , 2.        , 6.        , 8.        ],
       [3.        , 3.33333333, 5.        , 5.33333333],
       [3.        , 4.        , 7.        , 8.        ],
       [9.        , 4.        , 6.        , 0.        ]])

# Q5: 1174. Min max normalization




Rescale a numeric feature to the range `[0, 1]` using min-max normalization.

$$x'_i = \frac{x_i - \min(x)}{\max(x) - \min(x)}$$

**Input**
```
x = [1, 2, 3, 4, 5]
```
**Expected Output**
```
[0.0, 0.25, 0.5, 0.75, 1.0]
```

In [3]:
import numpy as np

def min_max_normalize(x):
    """
    Applies min-max normalization to a 1D feature vector.

    Args:
        x (list[float]): Input values.

    Returns:
        list[float]: Normalized values in the range [0, 1].
    """
    x = np.array(x)
    return ( x - np.min(x)) / (np.max(x) - np.min(x))

# Example Usage
x = [10,20,15,25]
result = min_max_normalize(x)
result

array([0.        , 0.66666667, 0.33333333, 1.        ])

# Q6 :861. Downsample Majority Class




Downsample the majority class of binary labels (`0` and `1`) to reduce class imbalance.

Number of majority samples to keep:

$$k = \left\lfloor \frac{n_{min}}{\max(\text{ratio},\ 10^{-12})} \right\rfloor$$

**Constraints**
- Keep all minority samples
- Randomly select `k` majority samples using `seed` (without replacement)
- Preserve original relative order in returned labels
- If `ratio >= 1` or `k > n_majority` → keep all majority samples

**Input**
```
labels = [0, 1, 0, 0, 1, 0, 0]
ratio  = 0.5
seed   = 42
```
**Expected Output**
```
[0, 1, 0, 1]
```

In [ ]:
import numpy as np

def downsample_majority(labels: np.ndarray, ratio: float, seed: int) -> list:
    """
    Downsample the majority class to match the minority class ratio.

    Complexity: O(N) time, O(N) space
    """
    arr = np.asarray(labels)

    # Identify indices for each class
    # can use np.wehre(arr==0) also, but need to upack the tuple it sends.
    # np.flatnonzero -> retruns the index of the condition meets. 
    idx0 = np.flatnonzero(arr == 0)
    idx1 = np.flatnonzero(arr == 1)

    if len(idx0) == 0 or len(idx1) == 0:
        return arr.tolist()

    # Determine majority and minority
    min_idx, maj_idx = (idx0, idx1) if len(idx0) < len(idx1) else (idx1, idx0)
    n_min = len(min_idx)
    n_maj = len(maj_idx)

    # Calculate number of majority samples to keep
    if ratio >= 1.0:
        target_maj = n_maj
    else:
        # Formula: n_min / ratio. Avoid div by zero.
        target_maj = int(n_min / max(ratio, 1e-12))
        target_maj = min(target_maj, n_maj)

    # Randomly sample majority indices
    # Why default_rng instead of np.random.seed:


    # np.random.seed(42)      →  old API, global state
    #                             affects all random calls everywhere

    # np.random.default_rng(42) →  new API, local generator object
    #                             only affects calls on this rng object
    #                             safer, preferred in modern numpy
    #     rng = np.random.default_rng(seed)
    rng = np.random.default_rng(seed)
    keep_maj = rng.choice(maj_idx, size=target_maj, replace=False)

    # Combine, sort to preserve original order, and return
    keep_indices = np.concatenate([min_idx, keep_maj])
    keep_indices.sort()

    return arr[keep_indices].tolist()

# Platform requirement: Call the function at the end
seed = 7
ratio = 0.5
labels = [1,1,1,0]
downsample_majority(labels, ratio, seed)

[1, 1, 0]