# Q1: 960. Binning continuous variables




Turn a continuous feature into discrete bucket IDs using equal-width binning.

$$w = \frac{\max(x) - \min(x)}{\text{num\_bins}}$$

$$\text{bin}(x_i) = \left\lfloor \frac{x_i - \min(x)}{w} \right\rfloor$$

Clamp max value to last bin: $\text{bin}(x_{max}) = \text{num\_bins} - 1$

**Constraints**
- NumPy and Python built-ins only (no pandas, no scikit-learn)
- Return both `bin_ids` (integer) and `one_hot` encoding

**Input**
```
x        = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
num_bins = 3
```
**Expected Output**
```
bin_ids  = [0, 0, 0, 1, 1, 1, 2, 2, 2, 2]
one_hot  = [[1,0,0], [1,0,0], [1,0,0],
            [0,1,0], [0,1,0], [0,1,0],
            [0,0,1], [0,0,1], [0,0,1], [0,0,1]]
```

In [ ]:
import numpy as np

def bin_continuous_feature(x, num_bins):
    """
    Discretizes a continuous feature into equal-width bins.

    The bins span from min(x) to max(x), split into `num_bins`
    equal intervals. Each value is assigned a bin index in
    [0, num_bins - 1].

    Args:
        x (np.ndarray): 1D array of continuous values.
        num_bins (int): Number of bins to create.

    Returns:
        tuple[np.ndarray, np.ndarray]:
            - bin_ids: array of shape (len(x),), where each entry
              is the assigned bin index.
            - one_hot: array of shape (len(x), num_bins), each entry is a
              one-hot encoded vector.
    """
    # Ensure input is a numpy array
    x = np.array(x)

    # Compute range and bin width
    x_min = np.min(x)
    x_max = np.max(x)

    # Avoid division by zero if all values are the same
    if x_max == x_min:
         width = 1.0 # arbitrary, since resulting bin will be 0 anyway if we handle correctly
    else:
         width = (x_max - x_min) / num_bins

    if x_max == x_min:
         bin_ids = np.zeros_like(x, dtype=int)
    else:
         # Assign bin indices
         # Note: We want floor((val - min) / width)
         bin_ids = ((x - x_min) / width).astype(int)
         print(bin_ids)
         # Clamp indices to [0, num_bins - 1] to handle the max value case
         bin_ids = np.clip(bin_ids, 0, num_bins - 1)

    # Build one-hot encoding using advanced indexing
    one_hot = np.zeros((len(x), num_bins), dtype=int)
    print(one_hot)
    print(np.arange(len(x))) 
    one_hot[np.arange(len(x)), bin_ids] = 1 # this indexing I sould know

    return bin_ids, one_hot


# Example Usage
x = [1,2,2.9,3,4]
num_bins = 3
result = bin_continuous_feature(x, num_bins)
result

[0 1 1 2 3]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[0 1 2 3 4]


(array([0, 1, 1, 2, 2]),
 array([[1, 0, 0],
        [0, 1, 0],
        [0, 1, 0],
        [0, 0, 1],
        [0, 0, 1]]))