# Q1. 1293. Gradient clipping




Implement global norm gradient clipping, a common trick in optimization to prevent exploding gradients during training. Given a list of gradient vectors, you’ll scale them down only if their combined (global) L2 norm is too large.

The clipping rule is:

scale
=
min
⁡
(
1
,
 
max_norm
∑
i
∥
g
i
∥
2
2
)
,
g
i
′
=
scale
⋅
g
i
scale=min(1,  
∑ 
i
​
 ∥g 
i
​
 ∥ 
2
2
​
 
​
 
max_norm
​
 ),g 
i
′
​
 =scale⋅g 
i
​
 
Requirements
Implement the function

python
Copy
1
2
3
4
5
6
7
8
9
10
11
12
13
14
⌄
⌄
import numpy as np

def clip_gradients(grads, max_norm):
    """
    Applies global norm gradient clipping.

    Args:
        grads (list[np.ndarray]): A list of gradient vectors (each is a 1D np.ndarray).
        max_norm (float): The maximum allowed global L2 norm.

    Returns:
        list[np.ndarray]: Clipped gradients, same nested-list structure as `grads`.
    """
    # Your solution below
Rules:

Compute the global L2 norm across all gradients in grads (treat all entries as one long vector).
If the global norm is <= max_norm, return gradients unchanged (numerically, same values).
Otherwise, multiply every value in every gradient vector by a single shared scale.
Use NumPy for the math; don’t use any deep learning framework utilities.
Keep the output as a list of NumPy arrays.
Example
python
Copy
1
2
3
4
5
6
7
⌄
grads = [
    np.array([3.0, 4.0]),   # norm = 5
    np.array([0.0, 12.0])   # norm = 12
]
max_norm = 10.0

clip_gradients(grads, max_norm)
Output:

python
Copy
1
2
3
4
⌄
[
    array([2.3077, 3.0769]),
    array([0.0, 9.2308])
]


In [ ]:
import numpy as np

def clip_gradients(grads, max_norm):
    """
    Applies global norm gradient clipping.

    Args:
        grads (list[np.ndarray]): A list of gradient vectors (each is a 1D
            np.ndarray).
        max_norm (float): The maximum allowed global L2 norm.

    Returns:
        list[np.ndarray]: Clipped gradients, same nested-list structure as
            `grads`.
    """
    # Ensure inputs are arrays (in case lists are passed via tests)
    grads = [np.asarray(g, dtype=float) for g in grads]

    # Compute the global squared L2 norm
    total_sq = sum(np.sum(g**2) for g in grads)

    # Compute global L2 norm
    global_norm = np.sqrt(total_sq)

    # If within the limit, return a copy with same values
    if global_norm <= max_norm:
        return [g.copy() for g in grads]

    # Compute scaling factor
    scale = max_norm / global_norm

    # Scale all gradients
    return [g * scale for g in grads]

result = clip_gradients(grads, max_norm)
result

# Q2. 177. Least squares 1D closed form




You’ll derive and implement the closed-form solution for 1D least squares linear regression, a classic optimization problem where you fit a line to data by minimizing squared error. This checks if you can translate an objective into a simple, correct formula and implement it cleanly.

The objective is:

min
⁡
m
,
b
 
∑
i
=
1
n
(
y
i
−
(
m
x
i
+
b
)
)
2
m,b
min
​
   
i=1
∑
n
​
 (y 
i
​
 −(mx 
i
​
 +b)) 
2
 
Requirements
Implement the function

python
Copy
1
2
3
4
5
6
7
8
9
10
11
12
⌄
⌄
def least_squares_1d(x, y):
    """
    Computes the closed-form least squares fit for y ≈ m*x + b.

    Args:
        x (np.ndarray): 1D input values of length n.
        y (np.ndarray): 1D target values of length n.

    Returns:
        tuple[float, float]: (m, b) where m is slope and b is intercept.
    """
    # Your solution below
Rules:

Return the slope m and intercept b that minimize the sum of squared errors.
Use the standard closed-form solution (not iterative optimization like gradient descent).
Use NumPy for vectorized computation.
Don’t call any prebuilt linear regression utilities (e.g., np.polyfit, np.linalg.lstsq, scikit-learn).
Keep it in a single Python function.
Example
python
Copy
1
2
3
4
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 3.0, 5.0])

least_squares_1d(x, y)
Output:

python
Copy
1
(1.5, 0.3333333333333335)


In [ ]:
import numpy as np

def least_squares_1d(x, y):
    """
    Computes the closed-form least squares fit for y ≈ m*x + b.

    Args:
        x (np.ndarray): 1D input values of length n.
        y (np.ndarray): 1D target values of length n.

    Returns:
        tuple[float, float]: (m, b) where m is slope and b is intercept.
    """
    n = len(x)

    # Compute sufficient statistics using vectorized sums
    sum_x = np.sum(x)
    sum_y = np.sum(y)
    sum_xx = np.sum(x * x)
    sum_xy = np.sum(x * y)

    # Closed-form slope and intercept
    denom = n * sum_xx - sum_x * sum_x
    # Optionally handle division by zero or assume valid input per problem constraints
    m = (n * sum_xy - sum_x * sum_y) / denom
    b = (sum_y - m * sum_x) / n

    return m, b

result = least_squares_1d(x, y)
result

# Q3. 832. Minimize 1D quadratic Closed Form




You’ll derive and implement the closed-form minimizer of a simple 1D quadratic, which is a common warm-up in optimization interviews. Given coefficients, return the value of 
x
x that minimizes the function.

The quadratic function is defined as:

f
(
x
)
=
a
x
2
+
b
x
+
c
f(x)=ax 
2
 +bx+c
Requirements
Implement the function

python
Copy
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
⌄
⌄
import numpy as np

def minimize_quadratic_1d(a, b, c):
    """
    Finds the minimizer x* of a 1D quadratic function.

    The objective is:
        f(x) = a x^2 + b x + c

    Args:
        a (float): Quadratic coefficient.
        b (float): Linear coefficient.
        c (float): Constant term.

    Returns:
        float: The value x* that minimizes f(x).
    """
    # Your solution below
Rules:

Use the closed-form solution derived from setting the derivative to zero: 
f
′
(
x
)
=
2
a
x
+
b
f 
′
 (x)=2ax+b.
Return the minimizer 
x
∗
x 
∗
  (not the minimum value 
f
(
x
∗
)
f(x 
∗
 )).
Do not use iterative optimization methods (no gradient descent, no line search).
Use only NumPy and built-in Python libraries.
Keep everything inside this single function.
Example
python
Copy
1
2
a, b, c = 2.0, -8.0, 3.0
minimize_quadratic_1d(a, b, c)
Output:

python
Copy
1
2.0
Input Signature
Argument	Type
a	float
b	float
c	float


In [ ]:
import numpy as np

def minimize_quadratic_1d(a, b, c):
    """
    Finds the minimizer x* of a 1D quadratic function.

    The objective is:
        f(x) = a * x^2 + b * x + c

    Args:
        a (float): Quadratic coefficient.
        b (float): Linear coefficient.
        c (float): Constant term.

    Returns:
        float: The value x* that minimizes f(x).
    """
    # Set derivative 2 * a * x + b to zero and solve for x
    x_star = -b / (2.0 * a)
    return x_star

result = minimize_quadratic_1d(a, b, c)
result

# Q4. 625. Projection onto box constraints




Projecting a vector onto box constraints is a common step in constrained optimization and gradient-based methods. In this problem, you’ll implement the projection operator that “clips” each coordinate into a valid interval.

Π
[
l
,
u
]
(
x
)
i
=
min
⁡
(
max
⁡
(
x
i
,
 
l
i
)
,
 
u
i
)
Π 
[l,u]
​
 (x) 
i
​
 =min(max(x 
i
​
 ,l 
i
​
 ),u 
i
​
 )
Requirements
Implement the function

python
Copy
1
2
3
4
5
6
7
8
9
10
11
12
13
⌄
⌄
def project_onto_box(x, lower, upper):
    """
    Projects a vector onto box constraints (elementwise bounds).

    Args:
        x (np.ndarray): Input vector of length n.
        lower (np.ndarray): Lower bounds of length n.
        upper (np.ndarray): Upper bounds of length n.

    Returns:
        np.ndarray: Projected vector y where each y[i] is in [lower[i], upper[i]].
    """
    # Your solution below
Rules:

Project each element x[i] independently into the interval [lower[i], upper[i]].
Return a NumPy array (don’t modify the input arrays in-place).
Use only NumPy and Python built-in libraries (no SciPy or other helpers).
Keep it efficient: use vectorized NumPy operations.
Example
python
Copy
1
2
3
4
5
x = np.array([2.5, -1.0, 0.3, 10.0])
lower = np.array([0.0, 0.0, 0.0, 3.0])
upper = np.array([2.0, 5.0, 0.5, 7.0])

project_onto_box(x, lower, upper)
Output:

python
Copy
1
array([2.0, 0.0, 0.3, 7.0])
Input Signature
Argument	Type
x	np.ndarray
lower	np.ndarray
upper	np.ndarray
Output Signature
Return Name	Type
value	np.ndarray
Constraints
Use NumPy; no SciPy or helpers.
Return NumPy array.
Do not mutate inputs in-place.

In [ ]:
import numpy as np

def project_onto_box(x, lower, upper):
    """
    Projects a vector onto box constraints (elementwise bounds).

    Args:
        x (np.ndarray): Input vector of length n.
        lower (np.ndarray): Lower bounds of length n.
        upper (np.ndarray): Upper bounds of length n.

    Returns:
        np.ndarray: Projected vector y where each y[i] is in
            [lower[i], upper[i]].
    """
    # Clip each element to its [lower, upper] interval
    return np.clip(x, lower, upper)

result = project_onto_box(x, lower, upper)
result